### ISSUE TITLE
Investigate support for DRACO decoding

### ISSUE THREAD

**Issue by brentchow** [Svrf/SvrfGLTFSceneKit#11]
**Timebox:** 1d

## "Why"

Load times are immensely impactful to the user experience. From our user interviews, we found that users were frustrated and bored when content didn't load quickly. Users tap through content rapidly demanding fast load times.

[DRACO compression](https://google.github.io/draco/) can improve the loading times for 3D models over GZIP. 

- When , I want to , so I can .

*[Learn about Job Stories][JTBD]*

### The problem and goal

Problem: Loading times for 3D models are slow for users. We can decrease loading times by using DRACO compression, but we need to determine how/if we can support DRACO in SvrfGLTFSceneKit.

Goal: Determine if we can or can't add support for DRACO compressed GLBs in SvrfGLTFSceneKit.

## Knowns / possible solutions

- None known

### Additional Context

-  Related to: https://github.com/Svrf/svrf-wave/issues/2409

[JTBD]: https://jtbd.info/replacing-the-user-story-with-the-job-story-af7cdee10c27

**Comment by RomanFrom710** [comment]
I had some problems with building SvrfGLTFSceneKit. The shaders weren't included to the sample bundle resources.

Draco doesn't have swift library, but it can generate Xcode project with C++ files. Now I need to determine how to call C++ methods from Swift. Most likely it'll require objc wrapper. Also it would be nice to add compiled library instead of full draco source code.

**Comment by RomanFrom710** [comment]
I've found custom [swift draco package](https://github.com/3D4Medical/DracoSwiftPackage). It shows that it's possible to use draco in swift. However, these guys have their own [glTFSceneKit](https://github.com/3D4Medical/glTFSceneKit) implementation. So now I'm looking for a way to use draco library output in the `SvrfGLTFSceneKit`

**Comment by RomanFrom710** [comment]
Some notes about out Draco files:
- First of all, draco conversion doesn't work in out pipeline. Draco files in our cloud have the same size as `.glb` files. It happens because we pass `compressDracoMeshes: true` instead of `dracoOptions` object to the `gltf-pipeline`.
- I've played a bit with `gltf-pipeline` CLI and compressed some our GLTF models:

| Model | GLTF with assets | Compressed | Compression ratio |
| ------- | ------------------ | -------------- | --- |
| [Waffle](https://www.svrf.com/vr/Waffle/676147)         | 2.27Mb | 2.11Mb | 1.08 |
| [Bandana](https://www.svrf.com/vr/Bandana/978992) | 4.34Mb | 4.17Mb | 1.04 |
| [Doge](https://www.svrf.com/vr/Doge/676167) | 2.47Mb | 2.27Mb | 1.09 |

**Comment by brentchow** [comment]
oh interesting. Good find @RomanFrom710.

- So DRACO is shaving off less than 10% of the file size.
- We'll need to re-run the gltf-worker against all of the models.

**Comment by brentchow** [comment]
As per our convo, @RomanFrom710 is going to investigate compression to see if we can squeeze a better compression ratio out of models and also investigate other ways to possibly improve downloading and rendering times. He'll include notes tomorrow.

**Comment by calvertcreates** [comment]
Here's a couple models that are using our newer methods for compression and would provide a better test:

1. https://admin.svrf.com/#/media/988009
1. https://admin.svrf.com/#/media/978912
1. https://admin.svrf.com/#/media/978912

**Comment by RomanFrom710** [comment]
### Draco compression

I've tested three models mention above. `glb` and `gltf` sizes are almost the same, so I included only `gltf` info:

| Name | Original size (Mb) | Draco (Mb / rate) | Gzip (Mb / rate) | Draco + Gzip (Mb / rate) |
| ---- | ---- | ---- | ---- | ---- |
| [Flower Crown](https://www.svrf.com/vr/988009) | 4.29 | 3.82 / **1.12** | 2.45 / **1.75** | 2.19 / **1.96** |
| [Pink Glasses](https://www.svrf.com/vr/978912) | 4.22 | 4.04 / **1.04** | 2.69 / **1.57** | 2.56 / **1.65** |
| [Rhinestone Hat](https://www.svrf.com/vr/993133) | 4.80 | 4.64 / **1.03** | 3.29 / **1.46** | 3.16 / **1.52** |

However, a quite complicated model from the Gltf repo shows much better compression rate:

| Name | Original size (Mb) | Draco (Mb / rate) | Gzip (Mb / rate) | Draco + Gzip (Mb / rate) |
| ---- | ---- | ---- | ---- | --- |
| [Buggy](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy) | 7.75 | 1.07 (**7.24**) | 1.68 (**4.61**) | 0.64 (**12.1**) |

My guess is that Draco is good only with complicated models (got it from `gltf-pipeline --stats`):

| | Our [Rhinestone Hat](https://www.svrf.com/vr/993133) | The [Buggy](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy) |
| --- | --- | --- |
| Meshes | 2 | 109 |
| Materials | 2 | 148 |
| Rendered primitives | 10,266 | 278,672 |

### Splitting up `.bin`s
Yesterday we discussed with Brent that probably we can split buffers and for example load everything except blendshapes first and show a model without blendshapes until they're loaded. I've found a [tool](https://github.com/donmccurdy/glTF-Transform) to split them, but I'm having some problems with installing it for now. @calvertcreates is it possible to split up buffers when creating a model?

### Other improvements
- Using HTTP/2 - It's related more to iOS and Swift environment, haven't checked it yet.
- Minifying JSON - we store a lot of whitespaces in our GLTF files. We can minify them to save a couple of kilobytes.

**Comment by calvertcreates** [comment]
^^ I think this is pretty good, wdyt @brent?

**Comment by brentchow** [comment]
I've had some chats with @RomanFrom710, @jexe, and @calvertcreates.

There seems to be some agreements around the following:

- Draco isn't very effective for our models' meshes
- Splitting up the `.bin` files, while they're large, sounds complicated
- Textures could be optimized or shrunk to lower resolutions to help downloading times

@calvertcreates can we setup a ticket in https://github.com/Svrf/svrf-studios to upload a model with several different texture resolutions?

At this point, I don't think 3-4% gains using Draco is worth a lot of engineering hours.

**Comment by brentchow** [comment]
Spun this out into the tickets shown above ^ 

Closing this ticket, as we don't feel that 3-8% gains by draco are currently worth the engineering time. We can reopen this ticket if our meshes become more complex.
